users
danyaglebov98/dualboot_learning pull request #10
Opened 2020-05-06 15:22 UTC by danyaglebov98

2020-05-07 14:34 UTC, pn-y requested changes

2020-05-07 14:34 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :redirect
Такой тест не пойдет. Удалить создание пользователя из контроллера - тест все еще будет проходить.

2020-05-09 17:26 UTC, Andrew8xx8 requested changes

2020-05-09 17:26 UTC, Andrew8xx8 commented on test/controllers/web/developers_controller_test.rb
> +    assert_not_nil :developer
Что проверяет эта строка? Символ :developer всегда не nil

Предыдущее замечание пока не исправлено

2020-05-10 09:38 UTC, closed without merging