Feature maket
danyaglebov98/dualboot_learning pull request #11
Opened 2020-05-07 07:08 UTC by danyaglebov98

2020-05-07 14:39 UTC, pn-y requested changes

2020-05-07 14:39 UTC, pn-y commented on test/controllers/web/sessions_controller_test.rb
> +    assert_response :redirect
Такая же штука как с созданием. Проверяется какое то последствие удаления, а не удаление.

2020-05-09 17:29 UTC, Andrew8xx8 requested changes

2020-05-09 17:29 UTC, Andrew8xx8 commented on app/forms/session_form.rb
> +  def user_valid?
Нудно дать этому методу более осмысленное название. 

Этот метод проверяет, что учетная запись есть и логин пароль подходят. Логин и пароль можно назвать оним словом `credentials`. Ну и далее додумай название метода который проверяет это.

2020-05-10 09:38 UTC, closed without merging