Adminka
danyaglebov98/dualboot_learning pull request #16
Opened 2020-05-13 12:17 UTC by danyaglebov98

2020-05-13 18:33 UTC, mkalmykov requested changes

2020-05-13 18:33 UTC, mkalmykov commented on app/controllers/admin/users_controller.rb
> +      render :new_admin_user_url
Попробуй спровоцировать ошибку валидации и посмотреть, что будет.

2020-05-13 18:33 UTC, mkalmykov commented on app/controllers/web/boards_controller.rb
> +  def show
Попробуй пройтись по файлам рубокопом. Есть предположение, что линтер не проходит.

2020-05-13 18:33 UTC, mkalmykov commented on app/views/layouts/application.html.slim
> + doctype html
Лишних пробелы нужно убрать.

2020-05-13 18:33 UTC, mkalmykov commented on public/403.html
> +</html>
Настрой редактор, чтобы он добавлял пустую строку в конец файла автоматически.

2020-05-13 18:33 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +
Эта пустая строка лишняя.

2020-05-13 18:33 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    delete :destroy, params: {id: user.id }
Нужно, чтобы линтер проходил.

2020-05-13 18:33 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
Не хватает тестов на `create` и `update`.

2020-05-13 18:33 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    assert_response :redirect
Нужно проверить не только редирект, но и что юзер был удалён.

2020-05-14 11:05 UTC, pn-y requested changes

2020-05-14 11:05 UTC, pn-y commented on app/controllers/admin/users_controller.rb
> +      render(:new_admin_user_url)
Ты не поправил коммент Макса

2020-05-14 11:05 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    setup do
Кажется у тебя отступы неконсистентные с остальным приложением

2020-05-14 11:05 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +        assert_response :redirect
Не проверяется суть ™ метода.

2020-05-14 11:05 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +        assert_response :redirect
Не проверяется суть ™ метода.

2020-05-15 18:46 UTC, artempartos requested changes

2020-05-15 18:46 UTC, artempartos commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
не вижу что поправил

2020-05-15 19:36 UTC, artempartos approved these changes

2020-05-15 19:37 UTC, merged