Create tasks
danyaglebov98/dualboot_learning pull request #22
Opened 2020-06-01 08:47 UTC by danyaglebov98

2020-06-01 08:55 UTC, vdv73rus commented on package.json
> +    "react-is": "^16.13.1",
Что делает этот пакет?

2020-06-01 08:57 UTC, vdv73rus commented on package.json
> +    "webpacker-react": "^0.3.2"
Кажется, это не нужно в конечном бандле

2020-06-01 08:58 UTC, vdv73rus commented on app/javascript/repositories/TaskRepository.js
> +
Надо быть консистентным: или оставлять пустые строки, или нет

2020-06-01 09:04 UTC, vdv73rus commented on app/javascript/components/EditPopup/EditPopup.js
> +          action={
В Task.js action вычисляется в отдельную переменную, а тут нет. Надо сделать одинаково.

2020-06-01 09:06 UTC, vdv73rus commented on .eslintrc
> +      "max-len": ["error", {"code":128}]
В задании было что-то про 120 символов + посмотреть на предмет конфликтов с настройками prettier

2020-06-01 12:32 UTC, vdv73rus commented on app/javascript/components/AddPopup/AddPopup.js
> +          action={
do not pass jsx as is, calculate action above

2020-06-01 12:59 UTC, pn-y requested changes

2020-06-01 12:59 UTC, pn-y commented on app/controllers/responders/json_responder.rb
> +class Responders::JsonResponder < ActionController::Responder
А оно точно должно быть тут?

2020-06-01 12:59 UTC, pn-y commented on config/initializers/wrap_parameters.rb
> +  wrap_parameters :task, include: [:name, :description, :assignee_id, :state_event]
Ты уверен что это здесь должно быть?

2020-06-02 10:08 UTC, pn-y requested changes

2020-06-02 10:08 UTC, pn-y commented on app/controllers/api/application_controller.rb
> +    respond_to :json
Будто бы отступ неправильный

2020-06-02 10:08 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> -    task.destroy
Удаление отменяется?

2020-06-02 10:08 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +  const action = (
лучше группировать все штуки с JSX вместе

2020-06-02 10:08 UTC, pn-y commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +        <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
onClick={handleLoadMore}

2020-06-02 10:08 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
можно менять автора?

2020-06-03 11:18 UTC, pn-y approved these changes

2020-06-03 18:55 UTC, merged