Task assignee
danyaglebov98/dualboot_learning pull request #23
Opened 2020-06-04 11:12 UTC by danyaglebov98

2020-06-05 12:27 UTC, pn-y requested changes

2020-06-05 12:27 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskPresenter from '../../presenters/TaskPresenter';
не надо использовать относительные пути вверх

2020-06-05 12:27 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +              value={task.assignee}
презентер потерял

2020-06-05 12:27 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      assignee: '',
assignee это не строка. При использовании приложухи он никогда не будет строкой. 
Постарайся сделать так чтоб тип поля не менялся в ходе работы приложения.

2020-06-06 19:05 UTC, helmq commented on app/javascript/components/AddPopup/AddPopup.js
> +              value={task.assignee}
не поправлено

2020-06-06 20:28 UTC, helmq requested changes

2020-06-06 20:28 UTC, helmq commented on app/javascript/components/EditPopup/EditPopup.js
> +                value={task.assignee}
Тут тоже нужно поправить

2020-06-06 20:28 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
> +  task: PropTypes.shape({
Используй презентер

2020-06-07 07:44 UTC, vdv73rus commented on app/javascript/components/EditPopup/EditPopup.js
> +import TaskPresenter from '../../presenters/TaskPresenter';
Абсолютные пути предпочтительнее отсносительных

2020-06-07 07:45 UTC, vdv73rus commented on app/javascript/presenters/UserPresenter.js
> +    asignee: PropTypes.arrayOf(PropTypes.string),
У модели юзера нет такого поля

2020-06-07 07:45 UTC, vdv73rus commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
Не нашёл использования этого метода в коде, он точно нужен?

2020-06-07 09:10 UTC, danyaglebov98 commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
https://learn.dualboot.ru/lessons/10/practice/2

2020-06-10 11:02 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
> +  task: PropTypes.shape({
Не поправлено

2020-06-11 05:19 UTC, helmq requested changes

2020-06-11 05:19 UTC, helmq commented on app/javascript/components/AddPopup/AddPopup.js
> +import Form from 'components/EditPopup/components/Form';
Если переиспользуешь форму, то стоит ее вынести в глобальный неймспейс к остальным компонентам

2020-06-11 05:19 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
> +        value={task.assignee}
Презентер

2020-06-11 10:37 UTC, helmq approved these changes

2020-06-12 05:37 UTC, merged