Feature
danyaglebov98/dualboot_learning pull request #3
Opened 2020-04-28 10:46 UTC by danyaglebov98

2020-04-28 12:07 UTC, pn-y requested changes

2020-04-28 12:07 UTC, pn-y commented on test/factories/users.rb
> +    type { "" }
Пустой тип - не валидные данные

2020-04-28 12:07 UTC, pn-y commented on test/factories/users.rb
> +    last_name { "MyString" }
Используй sequence для таких текстовых полей

2020-04-28 12:07 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id { 1 }
Если можно не опускаться до уровня something_id - не стоит этого делать.

Factory Bot умеет работать с ассоциациями как с сущностями.

Но их не стоит создавать каждый раз - сделай их пустыми. Это нужно для того что бы не создавалось по 100500 сущностей при вызове фабрики.

Сделай отдельные трейты где бы создавался auther или assignee

2020-04-28 13:00 UTC, danyaglebov98 commented on test/factories/users.rb
> +    type { "" }
так я все делал по инструкции курса

2020-04-29 11:49 UTC, Andrew8xx8 commented
Пустые тесты надо удалить.

И в нескольких файлах некорректное форматирование, запусти `rubocop -a`, чтобы автоматически исправить и проверь, настроен ли у тебя запуск `rubocop` в редакторе, например.

2020-04-29 11:50 UTC, Andrew8xx8 commented
А еще из следующей задачи по практике, ссылка ведет на коммит на этот PR, а они должны быть разные  PR

2020-04-29 12:45 UTC, Andrew8xx8 requested changes

2020-04-29 12:45 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
все еще есть пустые тесты

2020-04-29 12:45 UTC, Andrew8xx8 commented on test/models/developer_test.rb
> +  # test "the truth" do
Этот тоже пустой тест

2020-04-29 12:45 UTC, Andrew8xx8 commented on test/models/manager_test.rb
> +  # test "the truth" do
И этот пустой тест

2020-04-29 12:45 UTC, Andrew8xx8 commented on test/models/task_test.rb
> +  # test "the truth" do
Этот тоже пустой тест

2020-04-29 12:45 UTC, Andrew8xx8 commented on test/models/user_test.rb
> +  # test "the truth" do
И этот, тоже пустой тест. Никогда не стоит коммитить пустые, не работающие, закомментированные куски кода или файлы.

2020-04-29 13:57 UTC, Andrew8xx8 approved these changes

2020-05-06 11:51 UTC, merged