Feature/mailer
danyaglebov98/dualboot_learning pull request #34
Opened 2020-06-22 18:26 UTC by danyaglebov98

2020-06-23 10:14 UTC, pn-y requested changes

2020-06-23 10:14 UTC, pn-y commented on app/assets/stylesheets/password_resets.scss
> +// Place all the styles related to the password_resets controller here.
Будто бы этот файл тебе не нужен

2020-06-23 10:14 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      render(:congratulation)
Нет такого экшона в контроллере

2020-06-23 10:14 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    return render(:error) if @user.password_reset_sent_at < 24.hours.ago
Бизнесовой логики не должно быть в контроллере

2020-06-23 10:14 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if @user.password_reset_sent_at < 24.hours.ago
Бизнесовой логики не должно быть в контроллере

2020-06-23 10:14 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      render(:error)
Нет такого экшона

2020-06-23 10:14 UTC, pn-y commented on app/helpers/password_resets_helper.rb
> +module PasswordResetsHelper
Не нужен тебе этот файл

2020-06-23 10:14 UTC, pn-y commented on app/models/user.rb
> +    self.password_reset_token = SecureRandom.urlsafe_base64
А если такой токен уже существует?

2020-06-23 10:14 UTC, pn-y commented on db/migrate/20200618092243_add_password_reset_to_users.rb
> +    add_column :users, :password_reset_token, :string
А если два одинаковых токена получатся?

2020-06-25 20:00 UTC, pn-y requested changes

2020-06-25 20:00 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    return render(:give_an_error_message) if @user.password_reset_token_is_dead?
Значит, если у юзера токен протухший - отрендерится give_an_error_message. В котором будет проверка что у юзера протухший токен и отрендерится give_an_error_message?

2020-06-25 20:00 UTC, pn-y commented on app/models/user.rb
> +    self.password_reset_token = SecureRandom.urlsafe_base64
Значит будет 500 при сохранении?

2020-06-30 20:43 UTC, artempartos requested changes

2020-06-30 20:43 UTC, artempartos commented on app/forms/reset_form.rb
> +  def user_valid?
нужно разделять методы которые проверяют и методы которые добавляют ошибки
по соглашению метод со знаком вопроса должен отмечать true или false
```
validate :check_user_presence

def check_user_presence
  errors.add(:email, "user wasn't found") unless user_valid?
end

def user_valid?
  user.present?
end
```
я бы так переписал

2020-06-30 20:43 UTC, artempartos commented on app/models/user.rb
> +  def del_password_reset_token_and_sent_at
именование хреновое

2020-06-30 20:43 UTC, artempartos commented on app/models/user.rb
> +    self.password_reset_token = SecureRandom.urlsafe_base64
не пойму зачем писать так
```
self.password_reset_token = nil
self.password_reset_token = SecureRandom.urlsafe_base64
```
зачем нужна первая строка? ты же в следюущей меняешь все равно

2020-07-01 10:33 UTC, artempartos approved these changes

2020-07-01 11:16 UTC, merged